export const CREATE_ADMIN = 'CREATE_ADMIN';
export const LOGIN = 'LOGIN';
export const LOGOUT= 'LOGOUT';
export const LOADING = 'LOADING';
export const ERROR = 'ERROR';
export const MESSAGE = 'MESSAGE';
export const CLEAR = 'CLEAR';
export const CLEARMESSAGE = 'CLEARMESSAGE';




export const ADD_PRODUCTS = 'ADD_PRODUCTS';







// GETTING


export const GET_POULTRY_PRODUCTS = 'GET_POULTRY_PRODUCTS';
export const GET_PIG_PRODUCTS = 'GET_PIG_PRODUCTS';
export const GET_ALL_STAFF= 'GET_ALL_STAFF';
export const GET_EGG_PRODUCTS = 'GET_EGG_PRODUCTS';
export const GET_CATFISH_PRODUCTS = 'GET_CATFISH_PRODUCTS';
export const GET_ADMIN = 'GET_ADMIN';





// DELETE


export const DELETE_POULTRY_PRODUCTS = 'DELETE_POULTRY_PRODUCTS';
export const DELETE_EGG_PRODUCTS = 'DELETE_EGG_PRODUCTS';
export const DELETE_PIG_PRODUCTS = 'DELETE_PIG_PRODUCTS';
export const DELETE_CATFISH_PRODUCTS = 'DELETE_CATFISH_PRODUCTS';
export const DELETE_STAFF= 'DELETE_STAFF';








// UPDATES

export const UPDATE_POULTRY_PRODUCTS = 'UPDATE_POULTRY_PRODUCTS';
export const UPDATE_PIG_PRODUCTS = 'UPDATE_PIG_PRODUCTS';
export const UPDATE_EGG_PRODUCTS = 'UPDATE_PIG_PRODUCTS';
export const UPDATE_CATFISH_PRODUCTS = 'UPDATE_CATFISH_PRODUCTS';
export const UPDATE_STAFF= 'UPDATE_STAFF';
export const UPDATE_PROFILE= 'UPDATE_PROFILE';




